#!/usr/bin/env python3
"""Build result.json, scorecard.md and evidence.md for every assessed system,
then comparison.md across systems. All numbers come from scripts/score.py.

Usage: python3 tools/build.py   (run from this folder)
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(ROOT))
SCORER = os.path.join(REPO, "scripts", "score.py")
sys.path.insert(0, os.path.join(REPO, "scripts"))
import score as msr  # noqa: E402

SYSTEMS = ["frappe", "directus", "discourse", "posthog", "n8n", "dify", "librechat",
           "hermes-agent", "openclaw", "opencode", "openhands"]
OTHER_RUN = {"directus": (2.5, 1.2, 2.3, False), "frappe": (2.4, 1.2, 2.1, False),
             "posthog": (2.2, 2.7, 2.3, True), "n8n": (2.1, 2.0, 2.1, True), "discourse": (2.1, 1.1, 2.1, False),
             "dify": (2.0, 1.6, 2.4, False), "opencode": (2.0, 1.3, 2.1, False), "openclaw": (2.0, 0.9, 2.3, False),
             "hermes-agent": (1.9, 1.4, 2.3, False), "openhands": (1.6, 1.1, 2.4, False)}


def f1(x):
    return "–" if x is None else f"{x:.1f}"


def build(system, criteria, order, titles):
    folder = os.path.join(ROOT, system)
    path = os.path.join(folder, "scores.json")
    data = json.load(open(path))
    js = subprocess.run([sys.executable, SCORER, path, "--json"], capture_output=True, text=True)
    if js.returncode:
        raise SystemExit(f"{system}: {js.stdout}{js.stderr}")
    result = json.loads(js.stdout)
    with open(os.path.join(folder, "result.json"), "w") as h:
        h.write(js.stdout)
    md = subprocess.run([sys.executable, SCORER, path], capture_output=True, text=True).stdout
    head = [f"# {data['product']}: MSR v0.3 scorecard", "",
            "Evaluator: Claude, single rater. Framework: rubric v0.3.0 in this repository.", "",
            data.get("scope_line", ""), "", "## Reading", "", data.get("reading", "_Not written._"), "",
            "## Limits", "", data.get("limits", ""), "", "---", ""]
    with open(os.path.join(folder, "scorecard.md"), "w") as h:
        h.write("\n".join(head) + md.split("\n", 2)[2] + "\n")
    ev = [f"# {data['product']} evidence", "", f"Read at {data['source']} on {data['date']}. Grade A is code at the tip, B is in-repository documentation.", ""]
    dim = None
    for cid in order:
        if criteria[cid]["dim"] != dim:
            dim = criteria[cid]["dim"]
            ev += [f"## {dim} {titles.get(dim, '')}", ""]
        e = data["scores"][cid]
        st = e["status"]
        if st == "assessed":
            head_txt = f"**{e['score']}** (grade {e['grade']})"
            if "available_score" in e:
                head_txt += f", **{e['available_score']}** with opt-in settings"
            body = e["evidence"]
        elif st == "not_evidenced":
            head_txt, body = "**not evidenced**", "Searched: " + e["searched"]
        else:
            head_txt, body = "**not applicable**", e["rationale"] + (f" If counted: {e['if_applicable']}." if "if_applicable" in e else "")
        ev.append(f"- **{cid} {criteria[cid]['title']}**: {head_txt}. {body}")
        if "alt_score" in e:
            ev.append(f"  - Alternate reading {e['alt_score']}: {e.get('alt_note', '')}")
    with open(os.path.join(folder, "evidence.md"), "w") as h:
        h.write("\n".join(ev) + "\n")
    return data, result


def main():
    criteria, order, titles, model = msr.load_rubric(os.path.join(REPO, "references", "rubric.md"))
    v02 = json.load(open(os.path.join(HERE, "v02_comparison.json")))["systems"]
    rows = {s: build(s, criteria, order, titles) for s in SYSTEMS}
    L = ["# Comparison: rubric v0.3", "", "Generated by `tools/build.py`. Every number comes from `scripts/score.py`.", "",
         "## Indexes (default configuration)", "",
         "| System | Archetype | Malleability | Governance | Learning | Factory | Learning range | Closed loop (default / opt-in) |",
         "|---|---|---:|---:|---:|---:|---|---|"]
    order_sys = sorted(SYSTEMS, key=lambda s: -(rows[s][1]["indexes"]["learning"] or 0))
    for s in order_sys:
        d, r = rows[s]
        i, rg = r["indexes"], r["ranges"]["learning"]
        L.append(f"| {d['product']} | {d['archetype']} | {f1(i['malleability'])} | {f1(i['governance'])} | {f1(i['learning'])} | "
                 f"{f1(i['factory'])} | {f1(rg[0])}–{f1(rg[1])} | {'yes' if r['closed_loop_candidate'] else 'no'} / "
                 f"{'yes' if r['variants']['available']['closed_loop_candidate'] else 'no'} |")
    L += ["", "## Opt-in settings", "", "Indexes when shipped but off-by-default settings are enabled.", "",
          "| System | Governance | Learning | Changed criteria |", "|---|---:|---:|---|"]
    for s in SYSTEMS:
        d, r = rows[s]
        changed = [c for c, e in d["scores"].items() if "available_score" in e]
        if changed:
            av = r["variants"]["available"]["indexes"]
            L.append(f"| {d['product']} | {f1(r['indexes']['governance'])} → {f1(av['governance'])} | "
                     f"{f1(r['indexes']['learning'])} → {f1(av['learning'])} | {', '.join(changed)} |")
    L += ["", "## Closed-loop stages that fail by default", "", "| System | Failing stages |", "|---|---|"]
    for s in SYSTEMS:
        d, r = rows[s]
        fails = [f"{st['stage']} ({'/'.join(st['criteria'])})" for st in r["closed_loop"] if not st["passed"]]
        L.append(f"| {d['product']} | {', '.join(fails) or 'none'} |")
    L += ["", "## Profiles (default)", "", "| System | " + " | ".join(model["profiles"]) + " |", "|---|" + "---:|" * len(model["profiles"])]
    for s in SYSTEMS:
        d, r = rows[s]
        L.append(f"| {d['product']} | " + " | ".join(f1(r["profiles"][p]) for p in model["profiles"]) + " |")
    L += ["", "## Same systems under v0.2", "",
          "v0.2 had one Self-Evolution index that averaged change control (F) with observe and advise (J, M). "
          "v0.3 reports Governance (E, F) and Learning (J, M, P) separately, so the columns are not directly comparable.", "",
          "| System | v0.2 Self-Evolution (this rater) | v0.2 Self-Evolution (other run) | v0.3 Governance | v0.3 Learning |", "|---|---:|---:|---:|---:|"]
    for s in SYSTEMS:
        d, r = rows[s]
        other = OTHER_RUN.get(s)
        L.append(f"| {d['product']} | {f1(v02[s]['primary']['self_evolution'])} | {f1(other[1]) if other else '–'} | "
                 f"{f1(r['indexes']['governance'])} | {f1(r['indexes']['learning'])} |")
    with open(os.path.join(ROOT, "comparison.md"), "w") as h:
        h.write("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
